const sidebars = {
  // https://docusaurus.io/zh-CN/docs/sidebar/autogenerated
  mySidebar: [
    {
      type: 'category',
      label: '文',
      items: [
        {
          type: 'autogenerated',
          dirName: 'word',
        },
        // 'word/intro',
        // {
        //   type: 'category',
        //   label: '诗',
        //   items: [
        //     {
        //       type: 'autogenerated',
        //       dirName: 'word/poem',
        //     },
        //   ]
        // }
      ]
    }
    
  ],
};

module.exports = sidebars;
